packages <- c('ggplot2','cowplot','future','dplyr','ggwordcloud','limma','pcaMethods')
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager",repos="https://ftp.gwdg.de/pub/misc/cran/")
    BiocManager::install(packages)

install.packages('httr', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('plotly', repos="https://ftp.gwdg.de/pub/misc/cran/")
library(reticulate)
conda_install("r-reticulate", "pandas")
install.packages('Seurat', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('docopt', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('ggwordcloud', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('harmony', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('remotes', repos="https://ftp.gwdg.de/pub/misc/cran/")
install.packages('R.utils', repos="https://ftp.gwdg.de/pub/misc/cran/")
remotes::install_github('satijalab/seurat-wrappers')
remotes::install_github("mojaveazure/seurat-disk")
